dist: focal
language: node_js
node_js:
  - 16
  - 17
  - 18
before_script:
  - npm i ts-node
jobs:
  include:
    - stage: cover
      node_js: 19
      before_script:
        - npm i nyc --global
        - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C .
      script:
        - nyc npm test
        - nyc report --reporter=text-lcov > coverage/lcov.info && ./coveralls report