dist: focal
language: node_js
node_js:
  - 16
  - 17
  - 18
before_script:
  - npm i ts-node
jobs:
  include:
    - stage: cover
      node_js: 19
      script:
        - npm run cover
        - npm run coverage